os:
  - linux

language: php

php:
  - "7.1"

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  -php artisan key:generate
  -vendor/bin/phpunit --coverage-text

